// Verified publisher metadata and original figures; see local source audit.
window.PUBLICATIONS = [
  {
    "id": 1,
    "order": 1,
    "group": "en-journal",
    "year": 2026,
    "title": "An Explicit-Thinking LLM-Based Cognitive Apprenticeship Approach to Promote Students’ Metacognition, Higher Order Thinking Skills, and Learning Performance",
    "titleEn": null,
    "authors": "Yihua Zhong, Jili Chen, Changqin Huang, Xizhe Wang, Yixuan Chen, Tao He",
    "badge": "IEEE TLT",
    "publication": "IEEE Transactions on Learning Technologies, 19, 548–565",
    "roleZh": "（第一作者）",
    "roleEn": "(First author)",
    "doi": "10.1109/TLT.2026.3696968",
    "url": "https://ieeexplore.ieee.org/document/11535285/",
    "pdfUrl": null,
    "code": null,
    "image": "assets/papers/p1.png",
    "figureCaption": "Figure 2. Writing process based on the ETLLM-CA approach.",
    "figureSource": "https://ieeexplore.ieee.org/document/11535285/",
    "figureShort": "Zhong et al. · Fig. 2",
    "figureCredit": "Zhong et al. (2026), Fig. 2. IEEE Transactions on Learning Technologies. Original figure from the author’s final published PDF."
  },
  {
    "id": 2,
    "order": 2,
    "group": "zh-journal",
    "year": 2026,
    "title": "面向大语言模型系统能力培养的“三段式”实验教学设计——以ChatGLM-6B本地微调为例",
    "titleEn": "A three-stage laboratory teaching design for developing large language model systems competencies: A case study of local fine-tuning of ChatGLM-6B",
    "authors": "钟益华, 陈继力, 陈逸璇",
    "badge": "计算机教育",
    "publication": "计算机教育, (2), 23–28",
    "roleZh": "（第一作者）",
    "roleEn": "(First author)",
    "doi": "10.16512/j.cnki.jsjjy.2026.02.041",
    "url": "https://jyjs.cbpt.cnki.net/portal/journal/portal/client/paper/cd012c3ee66c14436b02205f2df37530",
    "pdfUrl": null,
    "code": null,
    "image": "assets/papers/p2.png",
    "figureCaption": "图1 “三段式”能力导向的大语言模型教学设计结构",
    "figureSource": "https://jyjs.cbpt.cnki.net/portal/journal/portal/client/paper/cd012c3ee66c14436b02205f2df37530",
    "figureShort": "钟益华等 · 图1",
    "figureCredit": "钟益华等（2026），图1，《计算机教育》。来自作者提供的正式论文。"
  },
  {
    "id": 3,
    "order": 3,
    "group": "en-journal",
    "year": 2025,
    "title": "Enhancing student reading performance through a personalized two-tier problem-based learning approach with generative artificial intelligence",
    "titleEn": null,
    "authors": "Changqin Huang, Yihua Zhong, Yongzhi Li, Xizhe Wang, Zhongmei Han, Di Zhang, Ming Liu",
    "badge": "HSSC",
    "publication": "Humanities and Social Sciences Communications, 12, 645",
    "roleZh": "（第二作者）",
    "roleEn": "(Second author)",
    "doi": "10.1057/s41599-025-04919-4",
    "url": "https://www.nature.com/articles/s41599-025-04919-4",
    "pdfUrl": "https://www.nature.com/articles/s41599-025-04919-4.pdf",
    "code": null,
    "image": "assets/papers/p3.png",
    "figureCaption": "Figure 3. Design of the PT-PBL approach.",
    "figureSource": "https://media.springernature.com/full/springer-static/image/art%3A10.1057%2Fs41599-025-04919-4/MediaObjects/41599_2025_4919_Fig3_HTML.png",
    "figureShort": "Huang et al. · Fig. 3",
    "figureCredit": "Huang et al. (2025), Fig. 3. Humanities and Social Sciences Communications. CC BY-NC-ND 4.0. Original figure, unmodified."
  },
  {
    "id": 4,
    "order": 4,
    "group": "zh-journal",
    "year": 2025,
    "title": "从单智能体到多智能体：大模型智能体支持下的激励型学习活动设计与实证研究",
    "titleEn": "From single-agent to multi-agent systems: Design and empirical study of motivational learning activities supported by large language model agents",
    "authors": "黄昌勤, 钟益华, 王希哲, 韩中美, 魏同权",
    "badge": "华东师大学报（教育科学版）",
    "publication": "华东师范大学学报（教育科学版）, 43(5), 44–56",
    "roleZh": "（第二作者）",
    "roleEn": "(Second author)",
    "doi": "10.16382/j.cnki.1000-5560.2025.05.004",
    "url": "https://xbjk.ecnu.edu.cn/CN/10.16382/j.cnki.1000-5560.2025.05.004",
    "pdfUrl": null,
    "code": null,
    "image": "assets/papers/p4.jpg",
    "figureCaption": "图2 基于多智能体的激励型学习活动设计",
    "figureSource": "https://xbjk.ecnu.edu.cn/fileup/1000-5560/FIGURE/2025-43-5/Images/2025-5-44/hdsfdxxbjykxb-2025-5-44-2.jpg",
    "figureShort": "黄昌勤等 · 图2",
    "figureCredit": "黄昌勤等（2025），图2，《华东师范大学学报（教育科学版）》。期刊官方原图。"
  },
  {
    "id": 5,
    "order": 5,
    "group": "en-journal",
    "year": 2024,
    "title": "ChatPRCS: A Personalized Support System for English Reading Comprehension Based on ChatGPT",
    "titleEn": null,
    "authors": "Xizhe Wang, Yihua Zhong, Changqin Huang, Xiaodi Huang",
    "badge": "IEEE TLT",
    "publication": "IEEE Transactions on Learning Technologies, 17, 1722–1736",
    "roleZh": "（第二作者）",
    "roleEn": "(Second author)",
    "doi": "10.1109/tlt.2024.3405747",
    "url": "https://ieeexplore.ieee.org/document/10539340/",
    "pdfUrl": null,
    "code": null,
    "image": "assets/papers/p5.png",
    "figureCaption": "Fig. 1. Structure of the ChatPRCS system.",
    "figureSource": "https://ieeexplore.ieee.org/document/10539340/",
    "figureShort": "Wang et al. · Fig. 1",
    "figureCredit": "Wang et al. (2024), Fig. 1. IEEE Transactions on Learning Technologies. Original figure from the author’s final published PDF."
  },
  {
    "id": 6,
    "order": 6,
    "group": "en-journal",
    "year": 2026,
    "title": "From Single-Agent System to Multi-Agent System: Design and Empirical Study on Motivational Learning Activities Supported by LLM-Based Agents",
    "titleEn": null,
    "authors": "Changqin Huang, Yihua Zhong, Xizhe Wang, Zhongmei Han, Tongquan Wei",
    "badge": "Frontiers of Education in China",
    "publication": "Frontiers of Education in China, 21(2), 105–125",
    "roleZh": "（第二作者）",
    "roleEn": "(Second author)",
    "doi": "10.3868/s110-021-026-0006-5",
    "url": "https://journal.hep.com.cn/fed/EN/10.3868/s110-021-026-0006-5",
    "pdfUrl": "https://journal.hep.com.cn/fed/EN/PDF/10.3868/s110-021-026-0006-5",
    "code": null,
    "image": "assets/papers/p6.png",
    "figureCaption": "Figure 2. Design of MAS-Based Motivational Learning Activities",
    "figureSource": "https://journal.hep.com.cn/fed/EN/PDF/10.3868/s110-021-026-0006-5",
    "figureShort": "Huang et al. · Fig. 2",
    "figureCredit": "Huang et al. (2026), Fig. 2. Frontiers of Education in China. Extracted from the publisher’s official PDF."
  },
  {
    "id": 7,
    "order": 7,
    "group": "en-journal",
    "year": 2026,
    "title": "UCMIB-PNS: Balancing Sufficiency and Necessity With Probabilistic Causality and Cross-Modal Uncertainty in Multimodal Sentiment Analysis",
    "titleEn": null,
    "authors": "Jili Chen, Yihua Zhong, Qionghao Huang, Changqin Huang, Fan Jiang, Xiaodi Huang, Xun Wang",
    "badge": "IEEE TAFFC",
    "publication": "IEEE Transactions on Affective Computing, 17(1), 92–106",
    "roleZh": "",
    "roleEn": "",
    "doi": "10.1109/taffc.2025.3606964",
    "url": "https://ieeexplore.ieee.org/document/11153045/",
    "pdfUrl": null,
    "code": "https://github.com/TheShy-Dream/UCMIB-PNS",
    "image": "assets/papers/p7.png",
    "figureCaption": "Fig. 2. Pipeline of UCMIB-PNS. The pipeline mainly consists of four parts: unimodal feature extraction, multimodal fusion, cross-view information bottleneck, and PNS balancing.",
    "figureSource": "https://ieeexplore.ieee.org/document/11153045/",
    "figureShort": "Chen et al. · Fig. 2",
    "figureCredit": "Chen et al. (2026), Fig. 2. IEEE Transactions on Affective Computing. Original figure from the author’s final published PDF."
  },
  {
    "id": 8,
    "order": 8,
    "group": "en-journal",
    "year": 2026,
    "title": "Investigating student engagement with personalised generative AI feedback: Effects on creative problem-solving and feedback uptake",
    "titleEn": null,
    "authors": "Yixuan Chen, Changqin Huang, Zhongmei Han, Di Zhang, Yiheng Lou, Yihua Zhong",
    "badge": "AJET",
    "publication": "Australasian Journal of Educational Technology, 42(4), 165–185",
    "roleZh": "",
    "roleEn": "",
    "doi": "10.14742/ajet.11512",
    "url": "https://ajet.org.au/index.php/AJET/article/view/11512",
    "pdfUrl": "https://ajet.org.au/index.php/AJET/article/download/11512/2322",
    "code": null,
    "image": "assets/papers/p8.png",
    "figureCaption": "Figure 1. Workflows of two GenAI feedback conditions",
    "figureSource": "https://ajet.org.au/index.php/AJET/article/download/11512/2322",
    "figureShort": "Chen et al. · Fig. 1",
    "figureCredit": "Chen et al. (2026), Fig. 1. Australasian Journal of Educational Technology. Extracted from the publisher’s official PDF."
  },
  {
    "id": 9,
    "order": 9,
    "group": "conference",
    "year": 2026,
    "title": "Effects of Personalized Generative AI on Student Creativity: Evidence from Creative Performance, Self-efficacy, and Attention Allocation",
    "titleEn": null,
    "authors": "Yixuan Chen, Xuemei Wu, Yihua Zhong, Changqin Huang",
    "badge": "ICTE 2025",
    "publication": "International Conference on Technology in Education (ICTE 2025). CCIS 2752, 376–388. Springer, 2026",
    "roleZh": "",
    "roleEn": "",
    "doi": "10.1007/978-981-95-4499-8_31",
    "url": "https://link.springer.com/chapter/10.1007/978-981-95-4499-8_31",
    "pdfUrl": null,
    "code": null,
    "image": "assets/papers/p9.png",
    "figureCaption": "Fig. 1. Interaction stages across standard and personalized GAI conditions.",
    "figureSource": "https://link.springer.com/chapter/10.1007/978-981-95-4499-8_31",
    "figureShort": "Chen et al. · Fig. 1",
    "figureCredit": "Chen et al. (2026), Fig. 1. ICTE 2025 proceedings, CCIS 2752. Extracted from the author-provided final PDF."
  }
];
